require: rubocop-rspec
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageChain:
  Enabled: true

Metrics/BlockLength:
  Max: 100
